# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "mm-general-tf-state-bucket-548894310305-us-east-1-an"
    encrypt = false
    key     = "dev/eks/terraform.tfstate"
    region  = "us-east-1"
  }
}
